# Generated by Django 5.1.15 on 2026-08-28 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, help_text='Código de cupón (NULL para promociones automáticas)', max_length=50, null=True, unique=True, verbose_name='Código')),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Porcentaje'), ('FIXED', 'Monto fijo')], max_length=10, verbose_name='Tipo de descuento')),
                ('value', models.DecimalField(decimal_places=2, help_text='Porcentaje (0-100) o monto fijo', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('starts_at', models.DateTimeField(verbose_name='Inicia en')),
                ('ends_at', models.DateTimeField(verbose_name='Termina en')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto mínimo de orden')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='NULL para ilimitado', null=True, verbose_name='Usos máximos')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Veces usado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('categories', models.ManyToManyField(blank=True, help_text='Vacío = aplica a todas', related_name='promotions', to='catalog.category', verbose_name='Categorías')),
                ('collections', models.ManyToManyField(blank=True, help_text='Vacío = aplica a todas', related_name='promotions', to='catalog.collection', verbose_name='Colecciones')),
                ('products', models.ManyToManyField(blank=True, help_text='Vacío = aplica a todos', related_name='promotions', to='catalog.product', verbose_name='Productos')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'db_table': 'promotions',
                'ordering': ['-starts_at'],
            },
        ),
    ]
