# Generated by Django 5.1.15 on 2026-08-28 17:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(help_text='Stripe event ID', max_length=64, unique=True, verbose_name='ID del evento')),
                ('event_type', models.CharField(max_length=64, verbose_name='Tipo de evento')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload')),
                ('processed_at', models.DateTimeField(blank=True, help_text='NULL hasta que se procese', null=True, verbose_name='Procesado en')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
            ],
            options={
                'verbose_name': 'Evento de Webhook Stripe',
                'verbose_name_plural': 'Eventos de Webhook Stripe',
                'db_table': 'stripe_webhook_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_id'], name='stripe_webh_event_i_6b18cc_idx'), models.Index(fields=['processed_at'], name='stripe_webh_process_a44f0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('CARD_ONLINE', 'Tarjeta en línea'), ('CASH', 'Efectivo'), ('CARD_POS', 'Tarjeta en POS'), ('QR', 'QR'), ('TRANSFER', 'Transferencia')], max_length=20, verbose_name='Método')),
                ('provider', models.CharField(choices=[('STRIPE', 'Stripe'), ('NONE', 'Ninguno')], default='NONE', max_length=20, verbose_name='Proveedor')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SUCCEEDED', 'Exitoso'), ('FAILED', 'Fallido'), ('REFUNDED', 'Reembolsado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('provider_payment_intent_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='ID de PaymentIntent')),
                ('provider_charge_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='ID de Charge')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Clave de idempotencia')),
                ('received_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Solo para pagos en efectivo', max_digits=12, null=True, verbose_name='Monto recibido')),
                ('change_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Solo para pagos en efectivo', max_digits=12, null=True, verbose_name='Cambio')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Respuesta del proveedor')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pagado en')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='payments_order_i_cdec7b_idx'), models.Index(fields=['status'], name='payments_status_d621e5_idx'), models.Index(fields=['provider_payment_intent_id'], name='payments_provide_668241_idx')],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(verbose_name='Número')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Emitido en')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='Archivo PDF')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='branches.branch', verbose_name='Sucursal')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='orders.order', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'db_table': 'receipts',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['branch', '-number'], name='receipts_branch__a78ef1_idx')],
                'unique_together': {('branch', 'number')},
            },
        ),
    ]
