# Generated by Django 5.1.15 on 2026-08-28 17:20

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('trade_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre Comercial')),
                ('tax_id', models.CharField(help_text='Número de Identificación Tributaria', max_length=50, unique=True, verbose_name='NIT')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del portal')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'suppliers',
                'ordering': ['legal_name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=14, unique=True, verbose_name='Código')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de recepción')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Número de factura')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('branch', models.ForeignKey(help_text='Sucursal que recibe la mercadería', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to='branches.branch', verbose_name='Sucursal')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts_received', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='suppliers.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Recepción de Compra',
                'verbose_name_plural': 'Recepciones de Compra',
                'db_table': 'purchase_receipts',
                'ordering': ['-created_at'],
            },
            bases=(core.models.CodeGeneratorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PurchaseReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo unitario')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.purchasereceipt', verbose_name='Recepción')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='catalog.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Ítem de Recepción',
                'verbose_name_plural': 'Ítems de Recepción',
                'db_table': 'purchase_receipt_items',
                'unique_together': {('receipt', 'variant')},
            },
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['branch', 'status'], name='purchase_re_branch__752f04_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['supplier'], name='purchase_re_supplie_11f43e_idx'),
        ),
    ]
