# Generated by Django 5.1.15 on 2026-08-29 19:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('gender', models.CharField(max_length=10, verbose_name='Género')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio base')),
                ('material', models.CharField(blank=True, max_length=200, verbose_name='Material')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado')),
                ('review_notes', models.TextField(blank=True, verbose_name='Notas de revisión')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_submissions', to='catalog.collection', verbose_name='Colección')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_submissions', to='suppliers.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Propuesta de producto',
                'verbose_name_plural': 'Propuestas de producto',
                'db_table': 'product_submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
