# Generated by Django 5.1.15 on 2026-08-28 17:20

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('branches', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=14, unique=True, verbose_name='Código')),
                ('scheduled_for', models.DateTimeField(help_text='Horario aproximado elegido por el cliente', verbose_name='Programado para')),
                ('expires_at', models.DateTimeField(help_text='Fecha límite para completar la reserva', verbose_name='Expira en')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PREPARING', 'Preparando'), ('READY', 'Listo para probador'), ('IN_FITTING', 'En probador'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado'), ('EXPIRED', 'Expirado'), ('NO_SHOW', 'No se presentó')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Notas')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='branches.branch', verbose_name='Sucursal')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='accounts.customerprofile', verbose_name='Cliente')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations_prepared', to=settings.AUTH_USER_MODEL, verbose_name='Preparado por')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservations',
                'ordering': ['-created_at'],
            },
            bases=(core.models.CodeGeneratorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('item_status', models.CharField(choices=[('HELD', 'Reservado'), ('TRIED', 'Probado'), ('PURCHASED', 'Comprado'), ('RETURNED_TO_FLOOR', 'Devuelto al piso')], default='HELD', max_length=20, verbose_name='Estado del ítem')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reservations.reservation', verbose_name='Reserva')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_items', to='catalog.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Ítem de Reserva',
                'verbose_name_plural': 'Ítems de Reserva',
                'db_table': 'reservation_items',
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['branch', 'status', 'scheduled_for'], name='reservation_branch__aa3e1f_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['customer', '-created_at'], name='reservation_custome_6c4ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'expires_at'], name='reservation_status_a113dc_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['code'], name='reservation_code_712a4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='reservation_expiry_valid'),
        ),
        migrations.AlterUniqueTogether(
            name='reservationitem',
            unique_together={('reservation', 'variant')},
        ),
    ]
