# Generated by Django 5.1.15 on 2026-08-28 17:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(error_messages={'unique': 'Ya existe un usuario con este correo electrónico'}, max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('first_name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=80, verbose_name='Apellido')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="El teléfono debe estar en formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{8,15}$')], verbose_name='Teléfono')),
                ('role', models.CharField(choices=[('CUSTOMER', 'Cliente'), ('ADMIN', 'Administrador'), ('BRANCH_MANAGER', 'Encargado de Sucursal'), ('CASHIER', 'Cajero'), ('SUPPLIER', 'Proveedor')], db_index=True, default='CUSTOMER', max_length=20, verbose_name='Rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('gender_preference', models.CharField(choices=[('MALE', 'Masculino'), ('FEMALE', 'Femenino'), ('UNISEX', 'Unisex'), ('KIDS', 'Niños')], default='UNISEX', max_length=10, verbose_name='Preferencia de género')),
                ('accepts_marketing', models.BooleanField(default=True, verbose_name='Acepta marketing')),
            ],
            options={
                'verbose_name': 'Perfil de Cliente',
                'verbose_name_plural': 'Perfiles de Cliente',
                'db_table': 'customer_profiles',
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('position', models.CharField(choices=[('MANAGER', 'Encargado'), ('CASHIER', 'Cajero'), ('STAFF', 'Personal')], max_length=20, verbose_name='Cargo')),
                ('employee_code', models.CharField(max_length=20, unique=True, verbose_name='Código de empleado')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de contratación')),
            ],
            options={
                'verbose_name': 'Perfil de Empleado',
                'verbose_name_plural': 'Perfiles de Empleado',
                'db_table': 'employee_profiles',
            },
        ),
    ]
