# Generated by Django 5.1.15 on 2026-08-28 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('branches', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='default_size_bottom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_bottom', to='catalog.size', verbose_name='Talla inferior preferida'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='default_size_top',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_top', to='catalog.size', verbose_name='Talla superior preferida'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='preferred_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_customers', to='branches.branch', verbose_name='Sucursal preferida'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='branches.branch', verbose_name='Sucursal'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['branch', 'position'], name='employee_pr_branch__d74002_idx'),
        ),
    ]
