# Generated by Django 5.1.15 on 2026-08-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(db_index=True, default='CUSTOMER', help_text='Código del rol asignado (RoleDefinition.code)', max_length=50, verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Identificador único, ej: catalog.products.view', max_length=100, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('module', models.CharField(blank=True, help_text='Agrupación para el front, ej: catalog, orders', max_length=50, verbose_name='Módulo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'app_permissions',
                'ordering': ['module', 'code'],
                'indexes': [models.Index(fields=['module', 'is_active'], name='app_permiss_module_3f7eb5_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Identificador del rol, ej: BRANCH_MANAGER', max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_system', models.BooleanField(default=False, help_text='Los roles del sistema no pueden eliminarse', verbose_name='Rol del sistema')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='accounts.apppermission', verbose_name='Permisos')),
            ],
            options={
                'verbose_name': 'Definición de Rol',
                'verbose_name_plural': 'Definiciones de Rol',
                'db_table': 'role_definitions',
                'ordering': ['name'],
            },
        ),
    ]
