# Generated by Django 5.1.15 on 2026-09-13 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


BITACORA_PERMISSION = (
    'bitacora.view',
    'Ver bitácora',
    'Consultar el registro de acciones de todos los módulos',
    'bitacora',
)


def seed_bitacora_permission(apps, schema_editor):
    AppPermission = apps.get_model('accounts', 'AppPermission')
    RoleDefinition = apps.get_model('accounts', 'RoleDefinition')

    perm, _ = AppPermission.objects.get_or_create(
        code=BITACORA_PERMISSION[0],
        defaults={
            'name': BITACORA_PERMISSION[1],
            'description': BITACORA_PERMISSION[2],
            'module': BITACORA_PERMISSION[3],
            'is_active': True,
        },
    )
    admin = RoleDefinition.objects.filter(code='ADMIN').first()
    if admin:
        admin.permissions.add(perm)


def unseed_bitacora_permission(apps, schema_editor):
    AppPermission = apps.get_model('accounts', 'AppPermission')
    AppPermission.objects.filter(code=BITACORA_PERMISSION[0]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_extend_rbac_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo del usuario')),
                ('user_full_name', models.CharField(blank=True, max_length=160, verbose_name='Nombre del usuario')),
                ('action', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de sesión'), ('LOGIN_FAILED', 'Inicio de sesión fallido'), ('REGISTER', 'Registro'), ('OTHER', 'Otra acción')], db_index=True, max_length=20, verbose_name='Acción')),
                ('module', models.CharField(db_index=True, max_length=50, verbose_name='Módulo')),
                ('resource', models.CharField(blank=True, max_length=80, verbose_name='Recurso')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='ID del objeto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='Método HTTP')),
                ('path', models.CharField(blank=True, max_length=255, verbose_name='Ruta')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_entries', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácora',
                'db_table': 'bitacora',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['-created_at'], name='bitacora_created_3b8e77_idx'),
                    models.Index(fields=['user', '-created_at'], name='bitacora_user_id_7bb38d_idx'),
                    models.Index(fields=['module', '-created_at'], name='bitacora_module_0d05e2_idx'),
                    models.Index(fields=['action', '-created_at'], name='bitacora_action_e61efb_idx'),
                ],
            },
        ),
        migrations.RunPython(seed_bitacora_permission, unseed_bitacora_permission),
    ]
