# Generated by Django 5.1.15 on 2026-09-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_bitacora'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='document_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='CI o NIT del cliente (aparece en el comprobante POS)', max_length=40, verbose_name='Número de documento'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='document_type',
            field=models.CharField(blank=True, choices=[('CI', 'Cédula de identidad'), ('NIT', 'NIT'), ('PASSPORT', 'Pasaporte'), ('OTHER', 'Otro')], default='', help_text='CI, NIT u otro documento fiscal para el comprobante', max_length=10, verbose_name='Tipo de documento'),
        ),
    ]
