# Generated by Django 5.1.15 on 2026-08-28 17:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('department', models.CharField(max_length=100, verbose_name='Departamento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'cities',
                'ordering': ['department', 'name'],
                'unique_together': {('name', 'department')},
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Código único de la sucursal (ej: SCZ-01)', max_length=10, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('opens_at', models.TimeField(verbose_name='Hora de apertura')),
                ('closes_at', models.TimeField(verbose_name='Hora de cierre')),
                ('fitting_rooms', models.PositiveSmallIntegerField(default=3, help_text='Número de probadores disponibles', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Probadores')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='branches.city', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'branches',
                'ordering': ['city__department', 'city__name', 'code'],
                'indexes': [models.Index(fields=['city', 'is_active'], name='branches_city_id_2fc18e_idx'), models.Index(fields=['code'], name='branches_code_95622b_idx')],
            },
        ),
    ]
