# Generated by Django 5.1.15 on 2026-08-28 17:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('on_hand', models.PositiveIntegerField(default=0, help_text='Unidades físicas en tienda', verbose_name='En mano')),
                ('reserved', models.PositiveIntegerField(default=0, help_text='Unidades comprometidas por reservas activas', verbose_name='Reservado')),
                ('min_threshold', models.PositiveIntegerField(default=0, help_text='Alerta de reposición', verbose_name='Umbral mínimo')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='branches.branch', verbose_name='Sucursal')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_stocks', to='catalog.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Stock por Sucursal',
                'verbose_name_plural': 'Stock por Sucursal',
                'db_table': 'branch_stock',
                'indexes': [models.Index(fields=['branch', 'variant'], name='branch_stoc_branch__6c770e_idx'), models.Index(fields=['variant', 'branch'], name='branch_stoc_variant_b025e4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('on_hand__gte', 0)), name='stock_on_hand_non_negative'), models.CheckConstraint(condition=models.Q(('reserved__gte', 0)), name='stock_reserved_non_negative'), models.CheckConstraint(condition=models.Q(('reserved__lte', models.F('on_hand'))), name='stock_reserved_lte_on_hand')],
                'unique_together': {('branch', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('IN_RECEIPT', 'Recepción de proveedor'), ('RETURN_IN', 'Devolución de cliente'), ('ADJUST_IN', 'Ajuste positivo'), ('TRANSFER_IN', 'Transferencia entrante'), ('RESERVE_HOLD', 'Reserva (bloqueo)'), ('RESERVE_RELEASE', 'Liberación de reserva'), ('OUT_SALE', 'Venta'), ('OUT_SALE_RESERVED', 'Venta de reserva'), ('ADJUST_OUT', 'Ajuste negativo'), ('TRANSFER_OUT', 'Transferencia saliente')], max_length=20, verbose_name='Tipo de movimiento')),
                ('quantity', models.PositiveIntegerField(help_text='Siempre positivo; el signo lo da el tipo', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('reference_type', models.CharField(choices=[('RESERVATION', 'Reserva'), ('ORDER', 'Orden'), ('RECEIPT', 'Recepción'), ('MANUAL', 'Manual'), ('TRANSFER', 'Transferencia')], max_length=20, verbose_name='Tipo de referencia')),
                ('reference_id', models.BigIntegerField(blank=True, help_text='ID del documento origen (Reservation, Order, etc)', null=True, verbose_name='ID de referencia')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Nota')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='branches.branch', verbose_name='Sucursal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='catalog.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'inventory_movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'created_at'], name='inventory_m_branch__d64ea0_idx'), models.Index(fields=['variant', 'created_at'], name='inventory_m_variant_23b28d_idx'), models.Index(fields=['reference_type', 'reference_id'], name='inventory_m_referen_ce9f4f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='movement_qty_positive')],
            },
        ),
    ]
