# Generated by Django 5.1.15 on 2026-08-28 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt_text', models.TextField(help_text='Solicitud original del usuario (voz transcrita)', verbose_name='Texto del prompt')),
                ('interpreted_spec', models.JSONField(blank=True, default=dict, help_text='Métrica, dimensión, filtros, rango interpretados por IA', verbose_name='Especificación interpretada')),
                ('result', models.JSONField(blank=True, default=dict, help_text='Datos del reporte generado', verbose_name='Resultado')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_requests', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud de Reporte',
                'verbose_name_plural': 'Solicitudes de Reporte',
                'db_table': 'report_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='report_requ_user_id_38f31f_idx')],
            },
        ),
    ]
