# Generated by Django 5.1.15 on 2026-08-28 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('USER', 'Usuario'), ('ASSISTANT', 'Asistente'), ('TOOL', 'Herramienta')], max_length=20, verbose_name='Rol')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('tool_calls', models.JSONField(blank=True, default=list, verbose_name='Llamadas a herramientas')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Clave de sesión')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado en')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Contexto de la conversación', verbose_name='Contexto')),
            ],
            options={
                'verbose_name': 'Sesión de Chat',
                'verbose_name_plural': 'Sesiones de Chat',
                'db_table': 'chat_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedding', models.JSONField(default=list, help_text='Vector de 768 dimensiones', verbose_name='Vector de embedding')),
                ('model_name', models.CharField(default='all-MiniLM-L6-v2', max_length=100, verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Embedding de Producto',
                'verbose_name_plural': 'Embeddings de Producto',
                'db_table': 'product_embeddings',
            },
        ),
        migrations.CreateModel(
            name='BrowsingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Clave de sesión')),
                ('event_type', models.CharField(choices=[('VIEW', 'Visualización'), ('SEARCH', 'Búsqueda'), ('ADD_CART', 'Agregar al carrito'), ('AR_TRY', 'Prueba AR'), ('RESERVE', 'Reserva')], max_length=20, verbose_name='Tipo de evento')),
                ('query', models.CharField(blank=True, max_length=200, verbose_name='Búsqueda')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ocurrido en')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='browsing_events', to='accounts.customerprofile', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Evento de Navegación',
                'verbose_name_plural': 'Eventos de Navegación',
                'db_table': 'browsing_events',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
