# Generated by Django 5.1.15 on 2026-08-28 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('ai', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsingevent',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='browsing_events', to='catalog.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='accounts.customerprofile', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.chatsession', verbose_name='Sesión'),
        ),
        migrations.AddField(
            model_name='productembedding',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='catalog.product', verbose_name='Producto'),
        ),
        migrations.AddIndex(
            model_name='browsingevent',
            index=models.Index(fields=['customer', '-occurred_at'], name='browsing_ev_custome_cc3beb_idx'),
        ),
        migrations.AddIndex(
            model_name='browsingevent',
            index=models.Index(fields=['session_key', '-occurred_at'], name='browsing_ev_session_3b0770_idx'),
        ),
    ]
