# Generated by Django 5.1.15 on 2026-08-28 17:20

import core.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('branches', '0001_initial'),
        ('catalog', '0002_initial'),
        ('promotions', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, help_text='Clave de sesión para usuarios invitados', max_length=40, null=True, unique=True, verbose_name='Sesión')),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='accounts.customerprofile', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('channel', models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Móvil'), ('POS', 'Punto de Venta')], max_length=10, verbose_name='Canal')),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pendiente de pago'), ('PAID', 'Pagado'), ('PREPARING', 'Preparando'), ('READY', 'Listo para retiro'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Reembolsado')], db_index=True, default='PENDING_PAYMENT', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento total')),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impuestos')),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('currency', models.CharField(default='BOB', max_length=3, verbose_name='Moneda')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pagado en')),
                ('branch', models.ForeignKey(help_text='Sucursal que vende o entrega', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='branches.branch', verbose_name='Sucursal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('customer', models.ForeignKey(blank=True, help_text='NULL para ventas anónimas en mostrador', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.customerprofile', verbose_name='Cliente')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='promotions.promotion', verbose_name='Promoción')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='reservations.reservation', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
            bases=(core.models.CodeGeneratorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio al momento de la venta', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio unitario')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Orden')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Ítem de Orden',
                'verbose_name_plural': 'Ítems de Orden',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart', verbose_name='Carrito')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='catalog.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Ítem de Carrito',
                'verbose_name_plural': 'Ítems de Carrito',
                'db_table': 'cart_items',
                'unique_together': {('cart', 'variant')},
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', '-created_at'], name='orders_branch__167245_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='orders_custome_12b615_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'channel'], name='orders_status_0e241d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['code'], name='orders_code_5b9ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['public_id'], name='orders_public__b44ebc_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('grand_total__gte', 0)), name='order_total_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'variant')},
        ),
    ]
