# Generated by Django 5.1.15 on 2026-08-28 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('RESERVATION_CREATED', 'Reserva creada'), ('RESERVATION_READY', 'Reserva lista'), ('ORDER_CONFIRMED', 'Orden confirmada'), ('ORDER_READY', 'Orden lista para retiro'), ('LOW_STOCK_ALERT', 'Alerta de stock bajo')], max_length=30, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('reference_type', models.CharField(blank=True, max_length=30, verbose_name='Tipo de referencia')),
                ('reference_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID de referencia')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leído')),
                ('sent_via_email', models.BooleanField(default=False, verbose_name='Enviado por email')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='branches.branch', verbose_name='Sucursal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx'), models.Index(fields=['branch', 'is_read', '-created_at'], name='notificatio_branch__9c20e9_idx')],
            },
        ),
    ]
